name: Deploy from Notion
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Clone loconotion
        run: git clone https://github.com/leoncvlt/loconotion.git loconotion-src

      - name: Install dependencies
        run: pip install -r loconotion-src/requirements.txt

      - name: Export Notion to HTML
       run: |
          PYTHONPATH=loconotion-src/loconotion python loconotion-src/loconotion/__main__.py \
              https://www.notion.so/36f1408d6cbb8069acf3e5f89fdc75e5 \
              --target ./out
    
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
